################################################################
##### Shop MySQL - ExternalSecret ###############################
# AWS Secrets Manager의 shop/mysql Secret에서EKS의 secret인 "shop-mysql-secret"을 생성/동기화
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: shop-mysql-external-secret
  namespace: shop

spec:

  # AWS Secrets Manager의 변경사항을 확인하는 주기
  refreshInterval: 1h

  # 위에서 생성한 SecretStore 사용
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore

  # ESO가 생성할 실제 Kubernetes Secret
  target:
    name: shop-mysql-secret

    # ExternalSecret 삭제 시 생성된 Kubernetes Secret도 함께 관리
    creationPolicy: Owner

  data:

    # AWS Secrets Manager
    # shop/mysql 내부의 "password" 값을 가져와
    # Kubernetes Secret의 "password" Key로 생성
    - secretKey: password
      remoteRef:
        key: shop/mysql
        property: password

    # AWS Secrets Manager
    # shop/mysql 내부의 "rootPassword" 값을 가져와
    # Kubernetes Secret의 "rootPassword" Key로 생성
    - secretKey: rootPassword
      remoteRef:
        key: shop/mysql
        property: rootPassword
