apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ .Values.mysql.persistence.claimName }}

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
