apiVersion: v1
kind: Secret

metadata:
  name: shop-mysql-secret

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  MYSQL_USER: {{ .Values.mysql.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
