# SecretStore는 "어디에서 Secret을 가져올 것인지"를 정의하는 리소스
apiVersion: external-secrets.io/v1
kind: SecretStore

metadata:
  name: aws-secrets-manager
  namespace: shop

spec:
  provider:
    aws:

      # AWS Secrets Manager 사용
      service: SecretsManager

      # Secrets Manager가 위치한 AWS Region
      region: ap-northeast-2
