clusterName: ekseks-project-eks
region: ap-northeast-2
vpcId: vpc-03452efc483b632a2

serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::356892573173:role/ekseks-project-aws-load-balancer-controller-role
