apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: aws-load-balancer-controller
  namespace: argocd

spec:
  project: default

  sources:
      #패키지는 AWS에서 제공하는 정식 Helm Chart 사용하여 설치
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: 1.13.4
      
      #설정 내용은, 별도 생성한 설정 파일 (아래 ref: values의 의미)
      helm:
        valueFiles:
          - $values/kubernetes/values/aws-load-balancer-controller.yaml

    # 2. 우리가 관리하는 Git Repository
    - repoURL: https://github.com/rlfrjs3/eks.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
