apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd

spec:
  project: default

  source:
    # External Secrets Operator 공식 Helm Repository
    repoURL: https://charts.external-secrets.io

    # Helm Chart 이름
    chart: external-secrets

    # 사용할 Helm Chart 버전
    targetRevision: 2.9.0

    helm:
      values: |
        # External Secrets Operator CRD 설치
        # SecretStore / ExternalSecret 등의 Custom Resource를사용할 수 있도록 CRD를 함께 설치
        installCRDs: true

        # Terraform에서 생성한 Pod Identity Association의ServiceAccount 이름과 반드시 동일해야 함
        serviceAccount:
          create: true
          name: external-secrets

  destination:
    server: https://kubernetes.default.svc

    # Terraform Pod Identity Association에서 지정한 Namespace와 동일해야 함
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      # Namespace가 없으면 ArgoCD가 자동 생성
      - CreateNamespace=true

      # ESO CRD가 큰 편이므로 Server-Side Apply 사용
      - ServerSideApply=true
