apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: observability
  namespace: argocd

  # Application 삭제 시 관리 리소스도 삭제하되 background 방식으로 처리
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 88.6.1

    helm:
      valuesObject:
        grafana:
          adminUser: admin
          adminPassword: "grafana-admin-2026"

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - Replace=true
