apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: observability
  namespace: argocd

  # Application 삭제 시, ArgoCD가 관리하던 monitoring 리소스도 같이 삭제
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    # Prometheus Community 공식 Helm Chart
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 88.6.1

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
