apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: shop-app
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io/background

spec:
  project: default

  source:
    repoURL: https://github.com/rlfrjs3/eks.git
    targetRevision: main
    path: kubernetes/shop-chart
    
    #ArgoCD가 helm 랜더링을 통해 flask-app을 만들고 배포
    helm:
      releaseName: shop-app

  destination:
    server: https://kubernetes.default.svc
    namespace: shop

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
