apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Values.ingress.name }}

  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.annotations.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.annotations.targetType }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
