apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: flask       #모니터하고자 하는  서비스의 label
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
