#1. flask-app의 ArgoCD 자동 Sync  중지 -> flask Ingress 삭제 후 ArgoCD가 리소스를 다시 생성하는 것을 방지
#2. flask Ingress 삭제 -> ALB 관련 AWS 리소스 삭제
#3. 최종 terraform destroy 
name: Ingress 삭제 + EKS 삭제 (Terraform)

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2


jobs: 
  terraform-destroy:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    defaults:
      run:
        working-directory: terraform

    steps:
    - name: 1. 깃헙 테라폼 레포에 있는 코드를 러너VM에 다운로드 
      uses: actions/checkout@v4

    - name: 2. AWS profile 인증 
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_GEON }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GEON }}
        aws-region: ap-northeast-2

    - name: 3. 러너VM에 테라폼 설치
      uses: hashicorp/setup-terraform@v3

    - name: 4. EKS kubeconfig 설정 
      run: | 
        aws eks update-kubeconfig --region ap-northeast-2 --name ekseks-project-eks

    - name: 5. flask-app  자동 Sync 중지
      run: | 
        kubectl patch application flask-app -n argocd --type merge -p '{"spec":{"syncPolicy":{"automated":null}}}'

    - name: 6. flask Ingress 삭제 및 ALB 삭제 대기
      run: |
        ALB_DNS=$(kubectl get ingress flask-ingress -n flask -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
        ALB_ARN=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?DNSName=='${ALB_DNS}'].LoadBalancerArn | [0]" --output text)
        echo "삭제 ALB ARN: $ALB_ARN"


        kubectl delete ingress flask-ingress -n flask --ignore-not-found=true --wait=false

        if [ "$ALB_ARN" != "None" ] && [ -n "$ALB_ARN" ]; then
          aws elbv2 wait load-balancers-deleted --load-balancer-arns "$ALB_ARN"
        fi

    - name: 7. 테라폼 초기화 (init)
      run: | 
        terraform init
 
    - name: 8. 테라폼 배포 계획 확인 (plan)
      run: | 
        terraform plan -destroy -out=destroy_plan
 
    - name: 9. 테라폼 실제 배포 (apply)
      run: | 
        terraform apply -auto-approve destroy_plan



