#AWS ALB 리소스는 ingress 삭제를 통해 삭제됨 (tf destroy 이전에 진행)


name: Ingress 삭제 + EKS 삭제 (Terraform)


#언제 작동할 것인가? -> 깃헙 사이트에서 [배포 버튼]을 누르면
on:
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2


jobs: 
  terraform-destroy:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    defaults:
      run:
        working-directory: terraform

    steps:
    - name: 1. 깃헙 테라폼 레포에 있는 코드를 러너VM에 다운로드 
      uses: actions/checkout@v4

    - name: 2. AWS profile 인증 
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_GEON }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GEON }}
        aws-region: ap-northeast-2

    - name: 3. 러너VM에 테라폼 설치
      uses: hashicorp/setup-terraform@v3

    - name: 4. EKS kubeconfig 설정 
      run: | 
        aws eks update-kubeconfig --region ap-northeast-2 --name ekseks-project-eks

    - name: 5. Ingress 삭제
      run: |
        kubectl delete ingress flask-ingress -n flask --ignore-not-found=true

    - name: 6. ALB 삭제 대기
      run: | 
        sleep 60

    - name: 7. 테라폼 초기화 (init)
      run: | 
        terraform init
 
    - name: 8. 테라폼 배포 계획 확인 (plan)
      run: | 
        terraform plan -destroy -out=destroy_plan
 
    - name: 9. 테라폼 실제 배포 (apply)
      run: | 
        terraform apply -auto-approve destroy_plan



