name: EKS 배포 (Terraform) &  ArgoCD 설치 + Git/ArgoCD 연동 (yaml 리소스 적용)


#언제 작동할 것인가? -> 깃헙 사이트에서 [배포 버튼]을 누르면
on:
  workflow_dispatch:

permissions:
  contents: write

env:
  AWS_REGION: ap-northeast-2

jobs: 
  terraform-deploy:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    defaults:
      run:
        working-directory: terraform

    steps:
    - name: 1. 깃헙 테라폼 레포에 있는 코드를 러너VM에 다운로드 
      uses: actions/checkout@v4

    - name: 2. AWS profile 인증 
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_GEON }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GEON }}
        aws-region: ap-northeast-2

    - name: 3. 러너VM에 테라폼 설치
      uses: hashicorp/setup-terraform@v3

    - name: 4. 테라폼 초기화 (init)
      run: | 
        terraform init
 
    - name: 5. 테라폼 배포 계획 확인 (plan)
      run: | 
        terraform plan 
 
    - name: 6. 테라폼 실제 배포 (apply)
      run: | 
        terraform apply -auto-approve

    - name: 7. EKS kubeconfig 설정
      run: | 
        aws eks update-kubeconfig --region ap-northeast-2 --name ekseks-project-eks 
 
    - name: 8. EKS 연결 확인
      run: | 
        kubectl get nodes

    - name: 9. ArgoCD 네임스페이스 생성 (없으면 생성, 있으면 그대로 유지)
      run: | 
        kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f - 

    - name: 10. ArgoCD 설치
      run: | 
        kubectl apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

    - name: 11. ArgoCD 설치완료 대기
      run: |  
        kubectl wait --for=condition=Available deployment/argocd-server -n argocd --timeout=300s

    - name: 12. ArgoCD root 애플리케이션 등록 (ArgoCD 와 Git 연동)
      run: | 
        kubectl apply -f ../kubernetes/bootstrap/root-app.yml
   
    - name: 13. AWS LB Controller 설정값 변경
      run: | 
        CLUSTER_NAME=$(terraform output -raw eks_cluster_name)
        VPC_ID=$(terraform output -raw vpc_id)
        LB_ROLE_ARN=$(terraform output -raw aws_lb_controller_role_arn)

        sed -i "s|__CLUSTER_NAME__|${CLUSTER_NAME}|g" ../kubernetes/values/aws-load-balancer-controller.yaml
        sed -i "s|__AWS_REGION__|${AWS_REGION}|g" ../kubernetes/values/aws-load-balancer-controller.yaml
        sed -i "s|__VPC_ID__|${VPC_ID}|g" ../kubernetes/values/aws-load-balancer-controller.yaml
        sed -i "s|__LB_ROLE_ARN__|${LB_ROLE_ARN}|g" ../kubernetes/values/aws-load-balancer-controller.yaml

    - name: 14. AWS LB Controller values Git Push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add ../kubernetes/values/aws-load-balancer-controller.yaml

        git diff --cached --quiet || \
        git commit -m "Update AWS LB Controller environment values"

        git push origin HEAD:main
