#flask 이미지 빌드 -> ECR push -> Helm values.yaml 수정 
name: Flask Application CI 

on:
  workflow_dispatch:

#Github Token이 push할 수 있도록 write 권한 부여
permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: 1. GitHub 소스 다운로드
      uses: actions/checkout@v4

    - name: 2. AWS 인증
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_GEON }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GEON }}
        aws-region: ap-northeast-2

    - name: 3. ECR 로그인
      uses: aws-actions/amazon-ecr-login@v2

    - name: 4. Docker 이미지 빌드
      run: |
        docker build -t flask-app:${{ github.sha }} ./app

    - name: 5. ECR push 하기 위해 이미지 태그 생성
      run: |
        docker tag flask-app:${{ github.sha }} \
        356892573173.dkr.ecr.ap-northeast-2.amazonaws.com/ekseks-project-app:${{ github.sha }}

    - name: 6. ECR Push
      run: |
        docker push \
        356892573173.dkr.ecr.ap-northeast-2.amazonaws.com/ekseks-project-app:${{ github.sha }}

    - name: 7. Helm values.yaml 수정 
      run: | 
        sed -i "s/^  tag: .*/  tag: ${{ github.sha }}/" kubernetes/flask-chart/values.yaml
        grep -A 2 "^image:" kubernetes/flask-chart/values.yaml

    - name: 8. Helm vaules.yaml 변경사항 Git push
      run: | 
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add kubernetes/flask-chart/vaules.yaml
        git commit -m "Update Flask image tag to ${{ github.sha }}"
        git push origin HEAD:main
